name: OpenMRS Automated Login Tests using Firefox

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium python-dotenv

      - name: Install Firefox
        run: sudo apt-get install -y firefox

      - name: Set up Geckodriver
        run: |
          wget "https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz"
          tar -xzf geckodriver-v0.35.0-linux64.tar.gz -C /usr/local/bin
          chmod +x /usr/local/bin/geckodriver
      - name: Run Selenium tests
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          URL: ${{ secrets.URL }}
          FIREFOX_LOCATION: '/usr/bin/firefox'
        run: |
          python task-gecko.py
